highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
timezone: Asia/Kolkata
title: DemonKingSwarn's Blog
description: Welcome to my weblog
author: DemonKingSwarn
permalink: /:year/:month/:day/:title
feed:
  path: /blog/feed.xslt.xml
